# Generated by Django 5.0.4 on 2026-04-27 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('avg_session_length', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_usage_snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
